### ISSUE TITLE
ImportError: Could not import 'config.schema.schema' for Graphene setting 'SCHEMA'. AttributeError: 'FilterSetOptions' object has no attribute 'order_by'.

### ISSUE THREAD

**Issue by lebeier** [graphql-python/graphene#369]
after upgrading my django to 1.10 and graphene to 1.1, I am getting the error in the title.

Anyone has any idea what does this suppose to mean?
