### ISSUE TITLE
Cannot Import JSONString

### ISSUE THREAD

**Issue by jwfehr** [graphql-python/graphene#345]
Running the latest version of Graphene, I cannot set a field to be a JSONString() type.

Accessing it via graphene.types.json.JSONString per documentation results in the following error:

AttributeError: 'module' object has no attribute 'json'

**Comment by yfilali** [comment]
Hi @jwfehr, could you please post a full code sample? Also, what version of graphene are you using?

Doing the following works fine with v1.0.2
```

from graphene.types.json import JSONString

class Foo(ObjectType):
    json = JSONString()
```

**Comment by jwfehr** [comment]
`    interests = graphene.types.json.JSONString()`

is an example of the lines throwing errors. I did however try the import like you have above and it worked for me.

**Comment by syrusakbary** [comment]
Thanks for keeping track of the issue @yfilali.
Closing the issue as it seems resolved.
