### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'subscription

### ISSUE THREAD

**Issue by Globegitter** [graphql-python/graphene#47]
I am trying to introspect a schema that worked fine with graphene `0.4.0.1` but now breaks with `0.4.2` (unchanged), getting the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "third_party/python/graphene/core/schema.py", line 126, in introspect
    return self.execute(introspection_query).data
  File "third_party/python/graphene/core/schema.py", line 117, in execute
    self.schema,
  File "third_party/python/graphene/core/schema.py", line 77, in schema
    subscription=self.T(self.subscription))
  File "third_party/python/graphene/core/schema.py", line 21, in __init__
    super(GraphQLSchema, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'subscription'
```

I am not using subscriptions right now in any way.

**Comment by Globegitter** [comment]
Ah sorry, I only updated `graphene` and forgot to update `graphql-core`.
