### ISSUE TITLE
Is it still possible to install 1.4.1 ?

### ISSUE THREAD

**Issue by Morreski** [graphql-python/graphene#601]
Hi,

I am currently working on an API that use `graphene==1.4.1`. Unfortunately, it crashes saying:

`graphql.error.located_error.GraphQLLocatedError: resolve_organization() missing 2 required positional arguments: 'context' and 'infos'`

Which is weird because it is a compatibility break introduced in v2.0 while my installed version is 1.4.1.

```python
import graphene
graphene.__version__ == '1.4.1'  # True
```

Am I missing something ?

**Comment by sf-sagarj** [comment]
yes it is possible. You will need to force the graphql-core version as well. We use following:

graphene == 1.4
graphql-core == 1.1

**Comment by Morreski** [comment]
I enforced the graphql-core version as you proposed and it works like a charm.

Thanks !
